name: Run jest

on:
  workflow_dispatch:
  push:

jobs:
  ci:
    name: Run jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install jest
#        run: yarn install --save-dev jest
        run: yarn install --save-dev jest

      - name: Run test
        run: yarn test

